variable "prefix" {}
variable "subnet_ids" {}
variable "vpc_id" {}
variable "sg_id" {}
variable "db_name" {}
variable "username" {}
variable "password" {}
variable "instance_class" {}
variable "port" {}
variable "engine_version" {}
variable "allocated_storage" {}
